/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define RCC_BASE	  0x40021000
#define RCC_CFGR	  *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR		  *(volatile uint32_t *)(RCC_BASE + 0x00)
#define	RCC_APB2ENR	  *(volatile uint32_t *)(RCC_BASE + 0x18)
#define GPIOA_BASE	  0x40010800
#define GPIOA_CRL	  *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH	  *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOB_BASE	  0x40010C00
#define GPIOB_CRL	  *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH	  *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOA_IDR	  *(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOB_ODR	  *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
//prototypes
void clock_init(void);
void GPIO_init(void);
void delay(int counter);

int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		//check if button connected with pinA1(PUR) is pressed
		if(((GPIOA_IDR & 1<<1) >> 1) == 0)
		{
			//toggle led connected with pinB1
			GPIOB_ODR ^= 1<<1;
			//single pressing
			while(((GPIOA_IDR & 1<<1) >> 1) == 0);
		}

		//check if button connected with pinA13(PDR) is pressed
		//Multi pressing
		if(((GPIOA_IDR & 1<<13) >> 13) == 1)
		{
			//toggle led connected with pinB13
			GPIOB_ODR ^= 1<<13;
		}
		delay(10000);
	}
}

void clock_init(void)
{
	//PLL multiplication factor by 8
	RCC_CFGR |= (0b0110<<18);
	//select PLL as a clock source
	RCC_CFGR |= (0b10<<0);
	//APB1 prescaler divided by 2
	RCC_CFGR |= (0b100<<8);
	//APB2 prescaler divided by 4
	RCC_CFGR |= (0b101<<11);
	//enable PLL
	RCC_CR |= 1<<24;
	//enable clock for GPIOA, GPIOB
	RCC_APB2ENR |= (0b11<<2);
}

void GPIO_init(void)
{
	//set pinA1 as input
	GPIOA_CRL = 0x0;
	GPIOA_CRL &= ~(0b11<<4);
	//set pinA1 as floating input
	GPIOA_CRL |= 1<<6;
	//set pinA13 as input
	GPIOA_CRH = 0x0;
	GPIOA_CRH &= ~(0b11<<20);
	//set pinA13 as floating input
	GPIOA_CRH |= 1<<22;
	//set pinB1 as output >>>>speed 10MHZ
	GPIOB_CRL = 0x0;
	GPIOB_CRL |= 1<<4;
	//set pinB1 as push_pull output
	GPIOB_CRL &= ~(0b11<<6);
	//set pinB13 as output >>>>speed 10MHZ
	GPIOB_CRH = 0x0;
	GPIOB_CRH |= 1<<20;
	//set pinB13 as push_pull output
	GPIOB_CRH &= ~(0b11<<22);
}

void delay(int counter)
{
	int i = 0;
	for(i=counter; i>0; i--);
}
