/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "stm32_f103c6_USART_drivers.h"


uint8_t Buffer;

void Usart_Handler_ISR(void)
{
	MCAL_UART_ReceiveData(USART1, &Buffer, disable);
	MCAL_UART_SendData(USART1, &Buffer, enable);
}

void clock_init(void)
{
	//Enable clock for GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock for GPIOB
	RCC_GPIOB_CLK_EN();
	//Enable clock for AFIO
	RCC_AFIO_CLK_EN();
}


int main(void)
{
	clock_init();
	USART_CONFIG_t UART_cfg;
	UART_cfg.USART_Mode = USART_MODE_TX_RX;
	UART_cfg.BaudRate_Speed = UART_BAUDRATE_SPEED_115200;
	UART_cfg.FLOW_CTRL = UART_FLOWCTRL_NONE;
	UART_cfg.Parity = UART_PARITY_DISABLE;
	UART_cfg.PayLoad_Data = UART_PAYLOAD_DATA_8BIT;
	UART_cfg.IRQ_ENABLE = UART_IRQ_ENABLE_RXNE;
	UART_cfg.Stop_bits = UART_STOP_BITS_1BIT;
	UART_cfg.P_IRQ_CallBack = Usart_Handler_ISR;
	MCAL_UART_Init(USART1, &UART_cfg);
	MCAL_UART_GPIO_Set_Pins(USART1);
    while(1)
    {

    }
}
