/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Header_Platform.h"

#define RCC_BASE	0x40021000
#define PORTA_BASE	0x40010800

#define APB2ENB				*((vuint32_t *)(RCC_BASE + 0x18))
#define GPIOA_CRH			*((vuint32_t *)(PORTA_BASE + 0x04))
#define GPIOA_ODR			*((vuint32_t *)(PORTA_BASE + 0x0c))

int main(void)
{
	APB2ENB |= 1<<2;
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		vuint32_t i;
		GPIOA_ODR |= 1<<13;
		for(i=0; i<5000; i++);		//delay
		GPIOA_ODR &= ~(1<<13);
		for(i=0; i<5000; i++);		//delay
	}
	return 0;
}


//====================================
//another method
/*
#include "Header_Platform.h"

#define RCC_BASE	0x40021000
#define PORTA_BASE	0x40010800

#define APB2ENB				*((vuint32_t *)(RCC_BASE + 0x18))
#define GPIOA_CRH			*((vuint32_t *)(PORTA_BASE + 0x04))

typedef union
{
	vuint32_t all_fields;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t pin13:1;
	}pin;

}R_ODR;

volatile R_ODR * porta = (volatile R_ODR *)(PORTA_BASE + 0x0c);

int main(void)
{
	APB2ENB |= 1<<2;
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		vuint32_t i;
		porta->pin.pin13 = 1;
		for(i=0; i<5000; i++);		//delay
		porta->pin.pin13 = 0;
		for(i=0; i<5000; i++);		//delay
	}
	return 0;
}
*/
