/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32_f103c6_gpio_drivers.h"
#include "stm32f103x6.h"

void clock_init(void)
{
	//enable clock for GPIOA
	RCC_GPIOA_CLK_EN();
	//enable clock for GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_init(void)
{
	GPIO_Pinconfig_t pin_cfg;
	//set pinA1 as floating input
	pin_cfg.PinNumber = GPIO_PIN_1 ;
	pin_cfg.Mode = GPIO_MODE_Input_FLU ;
	MCAL_GPIO_Init(GPIOA, &pin_cfg) ;
	//set pinA13 as floating input
	pin_cfg.PinNumber = GPIO_PIN_13 ;
	pin_cfg.Mode = GPIO_MODE_Input_FLU ;
	MCAL_GPIO_Init(GPIOA, &pin_cfg) ;
	//set pinB1 as push_pull output
	pin_cfg.PinNumber = GPIO_PIN_1 ;
	pin_cfg.Mode = GPIO_MODE_Output_PP ;
	pin_cfg.Output_speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB, &pin_cfg) ;
	//set pinB13 as push_pull output
	pin_cfg.PinNumber = GPIO_PIN_13 ;
	pin_cfg.Mode = GPIO_MODE_Output_PP ;
	pin_cfg.Output_speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB, &pin_cfg) ;
}

void delay(int counter)
{
	int i = 0;
	for(i=counter; i>0; i--);
}

int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		//check if button connected with pinA1(PUR) is pressed
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)
		{
			//toggle led connected with pinB1
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			//single pressing
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}

		//check if button connected with pinA13(PDR) is pressed
		//Multi pressing
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			//toggle led connected with pinB13
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		delay(10000);
	}
}
